name: linting test

on: 
  workflow_dispatch:

jobs:
  test-deploy:
    name: test linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: install commitlint
        run: npm install --save-dev @commitlint/travis-cli
      - name: configure commitlint to use conventional config
        run: echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
      - name: Lint commit message
        run: npm run commitlint --from HEAD~1 --verbose
