name: linting test

on: 
  pull_request:

jobs:
  test-deploy:
    name: test linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          fetch-depth: 0
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.x
      #     cache: npm
      # - name: Lint commit message
      #   run: npx commitlint --from HEAD~1 --verbose
      - uses: wagoid/commitlint-github-action@v5