name: linting test without PR

on: 
  pull_request:

jobs:
  test-deploy:
    name: test linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: install commitlint
        run: npm install --save-dev @commitlint/{cli,config-conventional}
      - name: Lint commit message
        run: npx commitlint --from HEAD~1 --verbose
